image:
  repository: ghcr.io/unitaryai/robodev/controller
  pullPolicy: Never
  tag: dev
config:
  ticketing:
    backend: ""
leaderElection:
  enabled: false
resources:
  limits:
    cpu: "1"
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 64Mi
service:
  type: NodePort
  nodePort: 30080
